### ISSUE TITLE
IOS 7:Crashes OOyalaSkinSDK

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#96] opened 2016-05-24 16:50 UTC
Hi 

For ios 8 and above we have ooyalaskin sdk to customize the player skin and for ios7 what can we do to customize the player skin.

**Comment by lental** [comment] 2016-05-24 17:46
Ooyala generally only supports the current and previous iOS version. In this case, we support iOS 9 and 8.

That being said, I was able to run the OoyalaSkinSampleApp on a 7.1.2, as well as successfully play back video. 

I will need more information into how it crashes, what the crash logs are, and what you're trying to do specifically.

Thanks,
Mike

**Comment by santhoshrajs** [comment] 2016-05-24 18:46
@lental 
if OoyalaSkinSDK won't support ios 7 means then how can we run this SDK in ios 7 devices.i am asking any alternative way is there to customize the player skin for ios 7

**Comment by lental** [comment] 2016-05-24 19:37
First, I can confirm that the OoyalaSkinSDK at least works on iOS 7.  Did you try running the iOS OoyalaSkinSampleApp on your iOS device?  If you did, and got a crash, you should provide the crash information here.  

Second, I say that we won't support iOS 7 overall means we will not provide fixes for any issues specifically for iOS 7.  To reiterate, iOS7 should work with the OoyalaSkinSampleApp.  I was able to confirm it working from our iOS7 devices.

Thirdly, there are three ways to customize Player UI:
1. Use the new Skin SDK, and either modify skin.json or fork the native-skin repository
2. Use the older UI, and modify the source code provided in the OoyalaSDK.zip.
3. Create your own Player UI from scratch, using the older UI source code as a guideline.

Those are your options for customization

**Comment by santhoshrajs** [comment] 2016-05-25 08:13
@lental 
iOS 7.1.1  used to executed for this sample app
I am able to play the videos but in the middle apps crashes 
Here i am attaching logs for reference:
OoyalaSkinSampleApp[1949:60b] **\* Assertion failure in -[CountdownView layoutSublayersOfLayer:], /SourceCache/UIKit/UIKit-2935.137/UIView.m:8794
2016-05-26 13:42:45.540 OoyalaSkinSampleApp[1949:60b] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Auto Layout still required after executing -layoutSubviews. CountdownView's implementation of -layoutSubviews needs to call super.'
**\* First throw call stack:
(0x2d6ccfd3 0x37f45ccf 0x2d6ccead 0x2e079d5b 0x2fee8e39 0x2fb6662b 0x2fb61e3b 0x2fb61ccd 0x2fb616df 0x2fb614ef 0x2fb5b21d 0x2d6982a5 0x2d695c49 0x2d695f8b 0x2d600f0f 0x2d600cf3 0x32559663 0x2ff4c16d 0x3a44d 0x38452ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by santhoshrajs** [comment] 2016-05-25 16:30
@lental 
please share me some example to customize the player skin for ios 7.it should be helpfull for me to proceed further.

**Comment by lental** [comment] 2016-05-25 17:48
okay! cool, I was able to reproduce based on your comments, and the issue seems self-explanatory.

I fixed it in the Skin SDK (see the referenced PR)

To workaround for now, you should be able to disable Up Next and Discovery Endscreen Timeout:

https://github.com/ooyala/skin-config/blob/master/skin.json#L135 set to false

https://github.com/ooyala/skin-config/blob/master/skin.json#L105 set to false

the Crash fix will be resolved and pushed in the next release

**Comment by santhoshrajs** [comment] 2016-05-25 17:58
@lental 
Will this change affect ios 8 and above version

**Comment by lental** [comment] 2016-05-25 18:06
not negatively. The fix will be tested thoroughly on 8 and 9, and any regression can be caught there.

you can look at the PR for yourself, and if you think that the change would negatively affect 8 and 9, let me know

**Comment by santhoshrajs** [comment] 2016-05-25 19:31
@lental 
Thanks for your great help.
Now i am able to play video in ios 7.1.1 but only thing if i tap share button apps crashes

Here i am attaching the crash logs for reference:
2016-05-27 01:01:01.287 OoyalaSkinSampleApp[2075:60b] -[UIActivityViewController popoverPresentationController]: unrecognized selector sent to instance 0x146e7b10
2016-05-27 01:01:01.289 [error][tid:main] Exception thrown while invoking show on target OOActivityView with params (
        {
        link = "http://debug.ooyala.com/?ec=h4aHB1ZDqV7hbmLEv4xSOx3FdUUuephx&pbid=d70e58f6e29446e883095e2f8abfca8b&reproSteps=1.%20";
        text = "MP4 Video";
    }
): -[UIActivityViewController popoverPresentationController]: unrecognized selector sent to instance 0x146e7b10
2016-05-27 01:01:01.293 OoyalaSkinSampleApp[2075:60b] **\* Terminating app due to uncaught exception 'RCTFatalException', reason: 'Message: Exception thrown while invoking show on target OOActivityView with params (...'
**\* First throw call stack:
(0x2d6ccfd3 0x37f45ccf 0x2d6ccf15 0xee551 0x10621d 0x105d0b 0x3842d833 0x3842d81f 0x3843449f 0x2d6978f1 0x2d6961c5 0x2d600f0f 0x2d600cf3 0x32559663 0x2ff4c16d 0x57495 0x38452ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

NOTE:I am not able to switch on CC option in both ios 7 and ios 8 and above

**Comment by santhoshrajs** [comment] 2016-05-25 19:36
Hi Sadam,


Just nowi verified the video playing now working fine but one problem is there in ios 7.if we click share button app crashes in ios 7 and working fine in ios 8 and above .i am raised this query to the support team .they will probably give the solution for this.


Thanks and Regards,

Santhosh Raj.S

________________________________

**Comment by lental** [comment] 2016-05-25 19:41
Closed Captions are only able to be switched on assets that have captions.  try the "VOD with Closed Captions" asset

**Comment by santhoshrajs** [comment] 2016-05-25 19:59
@lental 

For my understanding we need to upload the caption in dashboard so that it will reflect in our app right.
What about share button crash in ios 7

**Comment by santhoshrajs** [comment] 2016-05-26 03:33
@lental 
Any Updates on share button crash for ios 7

**Comment by lental** [comment] 2016-05-26 04:51
the share button crash will have to go through technical support  - That one seems harder to debug than the other one.  We will look into it but no promises on if it will get fixed

**Comment by santhoshrajs** [comment] 2016-05-30 13:32
@lental 
We have share button in the video player .is it possible to customize the share button so we we can give our own action from my end.

**Comment by santhoshrajs** [comment] 2016-06-01 16:37
@lental 

Any Updates on above queries?

**Comment by lental** [comment] 2016-06-01 17:57
The only way to customize the share button with your own actions is to fork the native-skin repo.  There is no way to enhance the share button through skin.json

**Comment by lental** [comment] 2016-06-01 18:14
Please direct all future questions through Support.  I'd like this issue to stay only around the crashing in iOS 7

**Comment by brol1dev** [comment] 2016-11-17 23:50
@lental, do we want to keep this one still opened?

**Comment by lental** [comment] 2016-12-05 16:39
no, we can close this now.  Our official stance is that we support the current iOS Version, and one below.  Since this is 4 versions out, we will not treat this as a bug that we plan on fixing.

Thanks,
Mike

**Closed as completed by lental** 2016-12-05 16:39 UTC
