### ISSUE TITLE
Ooyala iOS SDK binary ~40MB

### ISSUE THREAD

**Issue by benasher44** [ooyala/ios-sample-apps#79] opened 2016-04-05 17:22 UTC
Is there any particular reason why the binary is so big? We only use pieces related to just playing a video (no ads). Maybe this be split out into a subspec? This is our biggest dependency.

[The latest on github shows it as 38.4 MB.](/ooyala/ios-sample-apps/blob/stable/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK)

I could provide more guidance, but our tools for auditing a binary to give advice here are pretty limited. Maybe there's something that stands out on you all's end that's some low hanging fruit?

Thanks!

**Comment by benasher44** [comment] 2016-04-05 20:02
Brightcove seems to have helped with this by providing a [dynamic linking option for those that can support it.](/brightcove/brightcove-player-sdk-ios#readme) This cuts their binary in half relative to the size of the statically linked version.

**Comment by lental** [comment] 2016-04-05 20:54
a good question, but we have nothing in mind for this at the moment.  We can definitely investigate dynamic linking of our SDK, but no short term promises.

For a little context, an IPA of our BasicPlaybackSampleApp is "2,520,926 bytes (2.5 MB on disk)".  when an application is compiled with the Ooyala SDK, I don't expect a particularly large footprint.  Is that what you're currently optimizing for?  Is there anything particular you are targeting to reduce?

Thanks
Mike

**Comment by benasher44** [comment] 2016-04-05 22:10
@lental ah okay. Sounds like LTO is really helping out here, so we should be okay. Sounds like there aren't lots of static resources or anything like that.

Thanks!

**Comment by lental** [comment] 2016-04-07 21:49
no problem!  If you don't mind, I'm going to close this Issue.  Please reopen if you don't believe the issue is resolved.

Thanks,
Mike

**Closed as completed by lental** 2016-04-07 21:49 UTC
